payfunc/model-card

- Authorization/Creatable.spec.ts
- Authorization/Creatable.ts
- Authorization/index.ts
Changed name to `descriptor` of field for the text that goes on the statement.
> Changed name to descriptor.

- Authorization/index.spec.ts
- Authorization/index.ts
- Refund/index.ts
Forgot to att refund to Authorization
> Model refund

- .github/PULL_REQUEST_TEMPLATE/low-risk.md
Adds template for low risk pull requests.
Having a template simplifies doing things the right way.
None, change has no effect on the CDE.
> Added pull request template for low risk.

- .vscode/extensions.json
- Authorization/index.spec.ts
- package-lock.json
- package.json
- Added test for `Authorization.is` that includes `account` property.
- Added extensions recommendations to vscode configuration.
- Updated dependencies.
Ensure functionality is correct.
Except for the dependency update none as the the does not affect code run in production.
> Account test

- Account.spec.ts
Added unit test to test verification of production account tokens.
Ensure that test logic works also in production.
None, code does not affect production environment.
> Added verification of production account

- Authorization/Creatable/Safe.ts
- Authorization/Creatable/index.ts
- Authorization/index.ts
Added callback and verify for Creatable model.
For error tracing.
None.
> Authorization callback

- Card/index.ts
Added centralized id generator for card models.
Reduces risk of having wrong length of card id. 
Practically none.
> card id generator

- Merchant/Creatable.spec.ts
- Merchant/Creatable.ts
- Merchant/Emv3d/Protocol.ts
- Merchant/Emv3d/index.ts
Added protocol ch3d2 to emv3d for upcoming support of 3-D Secure v2.
To differentiate between 3-D Secure v1 ("ch3d1") and v2.
No impact until implemented.
> Preparing for emv3dv2

- Address/index.spec.ts
- Address/index.ts
- Customer/index.ts
- Email.ts
- PhoneNumber/index.spec.ts
- PhoneNumber/index.ts
- index.ts
Added customer information types for use with 3-D Secure Version 2.
More information can be supplied to 3-D Secure Version 2 compared to Version 1.
Providing type checks for customer data.
> Auth2 customer

- AuthorizationV2/Risk/Delivery.ts
- AuthorizationV2/Risk/GiftCard.ts
- AuthorizationV2/Risk/index.ts
Risk information type and sub-types Delivery and GiftCard added.
Risk assessment information that can be provided when user is trying to authenticate with 3-D Secure Version 2.
More risk information provided when used.
> Risk-info for use with 3-D Secure V2

- AuthorizationV2/Channel/Browser/Creatable.ts
- AuthorizationV2/Channel/Browser/index.ts
- AuthorizationV2/Channel/Sdk.ts
- AuthorizationV2/Channel/ThreeRi.ts
- AuthorizationV2/Channel/index.ts
Adding channel types for 3-D Secure Version 2.
For easy type checking of channel specific inputs used with 3-D Secure Version 2.
Adding checks that required fields of the used channel have correct values.
> Channel as type of system using 3-D Secure V2

- AuthorizationV2/Challenge/Creatable.ts
- AuthorizationV2/Challenge/Required.ts
- AuthorizationV2/Challenge/index.ts
Adding challenge information types, with different types used in different flows (challenge or frictionless flow) and stages when using 3-D Secure Version 2.
For easy identification of type of authentication flow.
Allows different authentication flow to use different types for easy identification of type of flow.
> Callback and challenge information

- Card/Change.ts
- Card/index.ts
Added type for a partial Card called Change with type check.
To make type check easier when updating cards.
Only type checking.
> Card change

- .circleci/config.yml
Improved message from CI script.
Improved bugging.
None.
> Print version number in message.

- Acquirer/index.ts
- Authorization/Creatable/Base.ts
- Authorization/Creatable/Safe.ts
- Authorization/Creatable/index.ts
- Authorization/index.ts
- AuthorizationV2/Challenge/index.ts
- AuthorizationV2/Channel/index.ts
- AuthorizationV2/Extension.ts
- AuthorizationV2/Risk/Delivery.ts
- AuthorizationV2/Risk/GiftCard.ts
- AuthorizationV2/Risk/index.ts
- Browser/Creatable.ts
- Browser/index.ts
- Capture/Creatable.ts
- Capture/index.ts
- Card/Expires/index.ts
- Card/index.ts
- Email.ts
- Merchant/Configuration/Card/index.ts
- Merchant/Configuration/Override.ts
- Merchant/Configuration/index.ts
- Merchant/Emv3d/index.ts
- Merchant/Key/index.ts
- Merchant/V1/Key/index.ts
- Merchant/index.ts
- PhoneNumber/index.ts
- Refund/index.ts
Step 2 of configuring eslint and prettierx. Only removing old tslint comments in this one.
Good tools when developing.
None on code that will execute. Only effects development.
> model tslint comments

- Browser/Creatable.ts
- Browser/index.ts
- Cancel/index.ts
- Capture/Creatable.ts
- Capture/index.ts
- Card/Change.spec.ts
- Card/Change.ts
- Card/Creatable.spec.ts
- Card/Creatable.ts
- Card/Expires/Month.ts
- Card/Expires/Year.ts
- Card/Expires/index.ts
- Card/Pan.ts
- Card/Scheme.ts
- Card/Token.spec.ts
- Card/Token.ts
- Card/Type.ts
- Card/index.ts
- Customer/index.ts
Part 2/3 of letting prettierx fix syntaxing according to our definitions.
More unified code standard.
None on code that will execute. Only effects development.
> step 2: B - C

- Browser/Creatable.ts
- package-lock.json
- package.json
Fixed bug affecting odd color depths.
Bug fix.
Minimal. It allows a few more color depths.
> Added possible color depths.

- Browser/Creatable.ts
Changes color depth from hardcoded values to string.
More than previous hardcoded values might be provided.
It will work without issues.
> Color depth number

- Verifier.ts
Fix bug of only production verifier working by awaiting all promises, then filtering.
Fixes a bug that disallowed development verifier to work.
No impact, works as intended
> Fix Verifier

- Card/Token.ts
- Card/index.ts
- package.json
Fix the verification target url to include the parent.
Original implementation lacked functionality.
No impact, fixes a non-working implementation.
> fix verification target url

- Card/Token.ts
- Card/index.ts
- Verifier.ts
Fix the verification target url to include the parent.
Original implementation lacked functionality.
No impact, fixes a non-working implementation.
> Verification target url branch 0.0

- Acquirer/Protocol.ts
- Acquirer/index.ts
Added "intergiro" type for acquirer protocol.
Necessary for integrating the new Intergiro acquirer.
No additional impact.
> Added intergiro acquirer protocol.

- Card/Scheme.ts
- Card/index.ts
Added type array for schemes.
We require it in worker-settlement to iterate over all schemes.
No impact. Just added a scheme type that can be iterated over.
> Export scheme type array

- .circleci/config.yml
- .github/workflows/build.yml
Moved the build step (basic test) from circleci to Github actions
Save credits on circleci
None
> Moved build to actions

- Key/Agent.spec.ts
- Key/Agent.ts
- Key/V1/index.spec.ts
- Key/V1/index.ts
- Key/index.spec.ts
- Key/index.ts
- Merchant/index.ts
- package-lock.json
Moved imports and exports of keys.
Removed circular dependencies.
Paths for keys have changed.
> Removed circular dependencies.
