payfunc/model-card

- Authorization/Creatable.spec.ts
- Authorization/Creatable.ts
- Authorization/index.ts
A `Authorization.Creatable` that does not contain any card data and therefore is "safe" to handle outside the PCI scope.
> Added creatable safe.

- Merchant/Creatable.spec.ts
- Merchant/Creatable.ts
- Merchant/Key.ts
Makes following properties `mcc`, `mid`, `bin` optional on merchants.
Properties are currently not needed for the function of the software itself.
Simpler to create new API keys.
> Made mid, mcc and bin optional.

- package-lock.json
- package.json
Updated authly dependency, responsible for encoding and decoding jwt. This will impact the verify functionality of this model. It will now add ability to spot url-encoded jwt `(can include "-" and "_" but not "+" or "/")` and correctly decode these as well as standard-encoded jwt `(can include "+" and "/" but not "-" or "_")`. Previously only possible to decode standard-encoded jwt.
To keep it in sync with the rest of the project that will go from signing and verifying standard-encoded jwt to url-encoded jwt.
Should have no immediate effects on the system, only add future verifying capabilities.
If not updating it might in the future have issues verifying some jwt encoded strings. Only risk would be failed jwt decoding which would result in unauthorized access which shouldn't happen …
> verify fix

- package-lock.json
- package.json
Updated authly dependency to include a crypto version for Internet Explorer 11.
Internet Explorer 11 has a different crypto version. Without the change, our UI:s won't run on Internet Explorer 11.
If the normal crypto doesn't exist, which is only the case for Internet Explorer 11, the msCrypto version will be used instead.
> Updated authly version with mscrypto

- Refund/index.ts
- tsconfig.json
Fixed spelling and configuration.
Now `model.Refund.is` works.
None.
> Fixes bug.

- AuthorizationV2/Change/Change02.ts
- AuthorizationV2/Change/Change03.ts
- AuthorizationV2/Change/Change04.ts
- AuthorizationV2/Change/Change05.ts
- AuthorizationV2/Change/Change06.ts
- AuthorizationV2/Change/Change07.ts
- AuthorizationV2/Change/index.spec.ts
- AuthorizationV2/Change/index.ts
- AuthorizationV2/Range/Range02.ts
- AuthorizationV2/Range/Range03.ts
- AuthorizationV2/Range/Range04.ts
- AuthorizationV2/Range/Range05.ts
- AuthorizationV2/Range/Range06.ts
- AuthorizationV2/Range/Range07.ts
- AuthorizationV2/Range/Range8099.ts
- AuthorizationV2/Range/index.ts
Added helper types very often used with 3-D Secure Version 2.
To provide easier type checking for "01" | "02"  ... "07" type of option parameters often used within 3-D Secure Version 2 protocol.
Avoiding a lot of code duplication and minimize code and risk of errors for programmer when doing almost the same thing multiple times.
> often used helper types

- AuthorizationV2/Extension.ts
Adding our version of the type `MessageExtension` specified in 3-D Secure Verison 2.
To be able to handle and send `MessageExtension` data.
Providing additional ability to handle and send information.
As `MessageExtension` type from 3-D secure api are defined as _"Data necessary to support requirements not otherwise defined in the 3-D Secure message"_, we will handle information being sent as parameters with type `MessageExtension` as if it might contain sensitive information according to our risk-analysis [3-D Secure v2 api added risks #215](https://github.com/cardfunc/projects/pull/215)
> Message extension

- Card/Token.ts
Renaming card.Token.type "authorization" to "single use" to further point out that it is a temporary token can only be used for one authorization.
Clarification.
Only a type name, so none.
> single_use

- Merchant/Configuration/Card.ts
- Merchant/Configuration/Override.ts
- Merchant/Configuration/index.spec.ts
- Merchant/Configuration/index.ts
- Merchant/Key.spec.ts
- Merchant/Key.ts
- Merchant/index.spec.ts
- Merchant/index.ts
Changed previous type model.Merchant.Configuration & { url: string, id?: string } to more easy to use types.
Need to inherit type model.Merchant.Configuration & { url: string, id?: string } elsewhere, so a simpler and clearer typing makes it easier to type check.
Same functionality.
> remade to make payfunc inheritance easier

- Merchant/V1/Key.ts
Changed configuration to card configuration on V1 merchant keys.
Missed name change in previous update.
Only difference is an optional id, so won't make a difference other than to avoid future confusion about why id is defined at all.
> Wrong configuration type.

- Card/Token.spec.ts
- Card/Token.ts
- Card/index.spec.ts
- Card/index.ts
Adding minimal safe card information to tokens for storing such info in order database for quick reference.
To have access to some card information when matching authorizations and orders.
Same information is already available, but api changes slightly and this information will be needed, but no major differences in what is stored and sent compared to before. No sensitive card information will be sent from cardfunc.
> Token info

- package-lock.json
- package.json
Added @babel/core package and removed babel-core.
@babel/core is the new version of Babel-core. Old Babel-core use an old version of Lodash with security issues.
No impact on functionality.
> Changed babel-core to @babel/core because of lodash security issue

- Card/Creatable.spec.ts
- Card/Creatable.ts
- Card/Token.spec.ts
- Card/Token.ts
Add verification type indicator and data to card creatable and to card token (except for token: no data allowed when type == "pares").
To add information about where in verification flow a card payment or account creation is. Only highly specified transaction id:s and similar data will be permissable as verification data. This update is also done to standardize verification data used with cards.
When verification type is "pares" then no verification data will be allowed in the card token. "is" method will fail if that is the case. It will because of that fail early in development to make it impossible to make a mistake ("is" check is always performed during verification of card tokens, which will fail verification already when testing).
This should have no increased risks on the system. …
> Card verification

- Card/Change.spec.ts
- Card/Change.ts
Added verification property from Card.Creatable to Card.Change (which is a Partial<Card.Creatable>).
Card.Change should mirror Card.Creatable, except that all properties should be optional.
Allows addition and removal of verification data of an existing card without having to provide all previous data.
> verification property added to Card.Change

- Card/Creatable.ts
- Card/Token.ts
Card verification will be able to store json-objects including properties other than of type strings.
Card verification needs to be able to store json-objects from responses to 3-D Secure Version 2 endpoints /auth or /postauth.
Less strict .is() checks, already stores part of responses of 3-D Secure version 2 endpoint information.
> Card verification must be able to store more types

- README.md
- package.json
Moved cardfunc/model to the Payfunc organization and therefore also needed to change its name to model-card and change name and documentation from cardfunc to payfunc and model to model-card.
We want to hold everything in one organization to reduce administration.
No impact on system.
> Renamed to model-card and bump minor version

- Account.spec.ts
- Authorization/index.spec.ts
- Card/Token.spec.ts
- Merchant/Key/KeyInfo.ts
- package-lock.json
- package.json
- verify.ts
Update `authly` dependency and allow unpacking with multiple audiences, including `account`.
`card-tokenizer` needs to unpack keys with audience `account`. This requires an update to the unpack function. To check for multiple audiences in one call of the verify function an update to `authly` is required.
Unpacking with multiple audiences has no impact except requiring less lines of code. Unpacking with audience `account` does not expose more information than the key itself exposes, as no encrypted fields get decrypted.
> Update authly; unpack multiple audiences.

- Merchant/Configuration/Card/KeyInfo.ts
- Merchant/Key/Audience.ts
- Merchant/Key/KeyInfo.spec.ts
- Merchant/Key/KeyInfo.ts
- Merchant/Key/index.ts
- Merchant/V1/Key/KeyInfo.ts
- Merchant/index.ts
Add audiences "agent" and "account" which is possible audiences in newer api-keys.
Need to be able to use new kind of audiences.
Minimal, as it will only add support for some newer api-keys.
> allow agent and account audiences on newer keys

- package-lock.json
- package.json
Updated Isoly to contain isoly.Date.
isoly.Date missing in import chains going back to model-card repository.
None, isoly.Date not used directly by model-card anywhere.
> bump isoly

- Card/Token.ts
- package-lock.json
- package.json
- tsconfig.test.json
Compile to es6 module.
Bump imports to es6 module imports.
Fixed tests by recompiling es6 modules to commonjs.
es6 modules allow us to use treeshaking in modules import this.
No impact as functionality is not changed.
> Change to es6 module

- Card/Token.ts
Converted seconds to milliseconds in JWT verification of Card.Token.
Date constructor uses epoch time in milliseconds, not seconds like JWT specification.
No impact.
> epoch seconds to milliseconds

- Card/Token.ts
- Verifier.ts
Parity to master 0.2.3 - Implements the same changes as the changes between 0.2.0 and 0.2.3
To use these changes in Azure Functions backends, we need to have a commonjs module of the same code.
No additional impact, refer to merge history of 0.2.x master branches.
> Parity to es6 branch

- package-lock.json
- package.json
Bump jest to newest version. Maintain on 0.0 branch. Set max-workers to 2 to fix tests running out of memory.
Remove reported security flaw of jest dependency node-notifier.
No impact, jest is only used in dev environment and for testing purposes.
> Bump jest 0.0 branch

- Card/Scheme.ts
Added types array with type annotation to model.Card.Scheme.
Prevents us from unnecessarily casting the type where we use it.
Type annotations don't have an impact on runtime.
> Scheme type type

- Card/Scheme.ts
Added types array with type annotation to model.Card.Scheme.
Prevents us from unnecessarily casting the type where we use it.
Type annotations don't have an impact on runtime.
> Type types 0.0

- Card/index.spec.ts
- Card/index.ts
Added information to model.Card about if csc matched or was present at point of conversion from model.Card.Creatable.
Could be useful information for merchant rule handling.
No sensitive information saved, only strings "matched", "mismatched" or "present". No impact.
> Csc matched 0.0

- Card/index.spec.ts
- Card/index.ts
Added information to model.Card about if csc matched or was present at point of conversion from model.Card.Creatable.
Could be useful information for merchant rule handling.
No sensitive information saved, only strings "matched", "mismatched" or "present". No impact.
> Csc matched

- Card/Change.ts
- Card/Creatable.ts
- Card/Pan.spec.ts
- package-lock.json
Add Pan typeguard to get better error feedback in case of incorrect PAN.
Currently, an incorrect PAN can in some cases be passed until 3ds enrolled requests, which leads to incorrect error statements.
No additional impact
> Apply pan typeguard

- Card/Change.ts
- Card/Creatable.ts
- Card/Pan.spec.ts
Add Pan typeguard to get better error feedback in case of incorrect PAN.
Currently, an incorrect PAN can in some cases be passed until 3ds enrolled requests, which leads to incorrect error statements.
No additional impact
> Apply pan typeguard parity

- Card/Token.ts
Added optional version parameter for method notification url:s. 
Needed to enforce 3dv2 auth version when some 3d secure related server doesn't support one version or the other.
No impact.
> Added optional version parameter for method callbacks

- Card/Token.ts
Added optional version parameter for method notification url:s. 
Needed to enforce 3dv2 auth version when some 3d secure related server doesn't support one version or the other.
No impact.
> Added optional version parameter for method callbacks - parity

- Key/Audience.ts
- Key/index.ts
- package-lock.json
Renamed `account` audience to `customer`.
The `account` audience had to change name.
No further impact.
> Renamed account.

- Card/index.ts
Exports the type array.
Needed to keep parity between the branches
No additional impact
> Export scheme type array - parity
